<a href="https://colab.research.google.com/github/tahreem636/Urban-Air-Quality-and-Health-Impact-Analysis/blob/main/Urban%20Air%20Quality%20and%20Health%20Impact%20Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
os.environ['KAGGLE_CONFIG_DIR']='/CONTENT/'

In [2]:
!kaggle datasets download -d abdullah0a/urban-air-quality-and-health-impact-dataset

Dataset URL: https://www.kaggle.com/datasets/abdullah0a/urban-air-quality-and-health-impact-dataset
License(s): MIT
Downloading urban-air-quality-and-health-impact-dataset.zip to /content
  0% 0.00/254k [00:00<?, ?B/s]
100% 254k/254k [00:00<00:00, 69.9MB/s]

In [3]:
import pandas as pd
df = pd.read_csv('/content/urban-air-quality-and-health-impact-dataset.zip')
df

,datetime,datetimeEpoch,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,City,Temp_Range,Heat_Index,Severity_Score,Condition_Code,Month,Season,Day_of_Week,Is_Weekend,Health_Risk_Score
0,2024-09-07,1.725692e+09,106.100000,91.000000,98.500000,104.000000,88.100000,95.900000,51.500000,21.000000,...,Phoenix,15.100000,95.918703,4.430000,NaN,9.0,Fall,Saturday,True,10.522170
1,2024-09-08,1.725779e+09,103.900000,87.000000,95.400000,100.500000,84.700000,92.300000,48.700000,21.500000,...,Phoenix,16.900000,92.281316,3.880000,0.0,9.0,Fall,Sunday,True,10.062332
2,2024-09-09,1.725865e+09,105.000000,83.900000,94.700000,99.900000,81.600000,90.600000,41.700000,16.900000,...,Phoenix,21.100000,90.599165,3.630000,0.0,9.0,Fall,Monday,False,9.673387
3,2024-09-10,1.725952e+09,106.100000,81.200000,93.900000,100.600000,79.500000,89.800000,39.100000,15.700000,...,Phoenix,24.900000,89.638811,2.851200,0.0,9.0,Fall,Tuesday,False,9.411519
4,2024-09-11,1.726038e+09,106.100000,82.100000,94.000000,101.000000,80.000000,90.000000,40.100000,15.900000,...,Phoenix,24.000000,89.760414,3.390800,0.0,9.0,Fall,Wednesday,False,9.515179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2024-09-18,1.726633e+09,76.060546,64.359387,69.002142,77.673823,63.510920,67.003338,59.936776,73.189130,...,Philadelphia,12.886665,71.837558,1.957318,NaN,9.0,Fall,Wednesday,False,8.750142
996,2024-09-17,1.726550e+09,68.409198,65.939319,66.567410,68.956722,64.805635,65.992526,59.010257,74.137401,...,San Diego,2.613629,72.463491,2.537413,0.0,9.0,Fall,Tuesday,False,9.118198
997,2024-09-12,1.726122e+09,69.756690,65.286919,65.919492,68.158536,63.662942,67.313322,62.024442,84.650482,...,San Diego,4.598936,67.560060,3.595470,NaN,9.0,Fall,Thursday,False,9.880093
998,2024-09-14,1.726284e+09,77.106797,61.481724,68.106569,76.426959,60.901526,68.094309,63.169608,86.860261,...,Los Angeles,15.477717,67.930437,3.498942,0.0,9.0,Fall,Saturday,True,9.561602
999,2024-09-18,1.726618e+09,90.923080,79.296868,81.636991,94.180423,78.071851,84.987113,73.393045,74.734715,...,Houston,11.017871,86.802712,3.040020,0.0,9.0,Fall,Wednesday,False,10.978044